language: cpp
compiler:
  - gcc
  - clang
before_script:
  - mkdir ../build
  - cd ../build
script:
  - cmake ../Lab_8_and_9
  - make -j
  - ./test/Test_Stack_Queue_List
notifications:
  email: false
